---
title: "MiSTer Controller Latency"
author: "Porkchop Express, Lemonici"
output:
  html_document:
    theme: cosmo
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(gsheet)
library(DT)
library(crosstalk)
```


```{r, echo=FALSE, warning=FALSE}
dat_raw <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1KlRObr3Be4zLch7Zyqg6qCJzGuhyGmXaOIUrpfncXIM/edit#gid=0')
dat <- dat_raw %>%
  mutate(Row = 2:(nrow(dat_raw) + 1)) %>%
  filter(`Valid Results` == "YES") %>%
  select(
    Make, Model, Device, Connection, "Wired/Wireless" = `Wired / Wireless`, "WirelessConnection" = `Wireless Connection`, `Home Button`,
    "Latency (in ms)" = `Average Measured Latency (in ms)`,
    "SD" = `Standard Deviation of Measured Latency (in ms)`,
    "Max" = `Max Measured Latency (in ms)`,
    "Min" = `Min Measured Latency (in ms)`,
    Category, `Face Buttons`, Row, `Date Added`
  ) %>%
  filter(!is.na('Latency (in ms)')) %>%
  arrange('Latency (in ms)') %>%
  mutate(
    `Missed` = ifelse('Latency (in ms)' < 100 / 6, Latency / (100 / 6), 1),
    `On Time` = 1 - Missed,
    ID = row_number()
  ) %>%
 distinct(Device, Connection, .keep_all = TRUE)
```

# Latency and Filters

You can find the full spreadsheet [here](https://docs.google.com/spreadsheets/d/1KlRObr3Be4zLch7Zyqg6qCJzGuhyGmXaOIUrpfncXIM/edit#gid=0). If you see a controller you'd like more info on, its row value listed here will match the "Detailed Results" tab.

```{r, echo=FALSE}
keep <- c("Device", "Latency (in ms)", "Category", "Connection", "Row")

shared_dat <- SharedData$new(dat)
bscols(widths = c(12),
  list(
    filter_select("Make", "Make", shared_dat, ~Make),
    filter_checkbox("Connection", "Connection", shared_dat, ~`Wired/Wireless`, inline = TRUE),
    filter_checkbox("Home Button", "Home Button", shared_dat, ~`Home Button`, inline = TRUE),
    filter_checkbox("Category", "Category", shared_dat, ~Category, inline = TRUE),
    filter_checkbox("Face Buttons", "Face Buttons", shared_dat, ~`Face Buttons`, inline = TRUE)
    )
  )

datatable(shared_dat,
            options = list(
              autowidth = TRUE,
              fixedColumns = TRUE,
              pageLength =  25,
              columnDefs = list(list(visible=FALSE, targets = (1:ncol(dat))[! names(dat) %in% keep]))
              )
          )
```

# Recently Added

```{r, echo=FALSE}
keep <- c("Date Added", "Device", "Latency (in ms)", "Category", "Connection", "Row")

chrono_dat <- dat_raw %>%
  mutate(Row = 2:(nrow(dat_raw) + 1)) %>%
  filter(`Valid Results` == "YES") %>%
  select(
    Make, Model, Device, Connection, "Wired/Wireless" = `Wired / Wireless`, "WirelessConnection" = `Wireless Connection`, `Home Button`,
    "Latency (in ms)" = `Average Measured Latency (in ms)`,
    "SD" = `Standard Deviation of Measured Latency (in ms)`,
    "Max" = `Max Measured Latency (in ms)`,
    "Min" = `Min Measured Latency (in ms)`,
    Category, `Face Buttons`, Row, `Date Added`
  ) %>%
  filter(!is.na('Latency (in ms)')) %>%
  arrange("Date Added") %>%
  mutate(
    `Missed` = ifelse('Latency (in ms)' < 100 / 6, 'Latency (in ms)' / (100 / 6), 1),
    `On Time` = 1 - Missed,
    ID = row_number()
  ) %>%
 distinct(Device, Connection, .keep_all = TRUE)



datatable(chrono_dat[rev(order(as.Date(chrono_dat$`Date Added`, format="%m/%d/%Y"))),], 
            options = list(
              autowidth = TRUE,
              fixedColumns = TRUE,
              pageLength =  20,
              columnDefs = list(list(visible=FALSE, targets = (1:ncol(dat))[! names(dat) %in% keep]))
              )
          )
```

# Static Plots

In all plots, the dashed red line corresponds to one frame

```{r, echo=FALSE}
dat$Device <- factor(dat$Device, levels = unique(dat$Device))
fit <- lm(data=dat, SD ~ `Latency (in ms)` + Min)
dat$Imputed <- is.na(dat$SD)
dat$SD[dat$Imputed] <- predict.lm(fit, dat[dat$Imputed,])

dat <- dat %>%
    mutate(
        `SD up` = `Latency (in ms)` + qnorm(.975) * SD,
        `SD down` = `Latency (in ms)` - qnorm(.975) * SD
    )
```


```{r, echo=FALSE, fig.height=10, warning=FALSE}
ggplot(dat, aes(x = `Wired/Wireless`, y = `Latency (in ms)`, color = `Wired/Wireless`)) +
  geom_boxplot() +
  scale_color_manual(values = c(`Wired` = '#2708A0', `Wireless` = '#F9C80E')) +
  theme(legend.position="none") +
  geom_hline(yintercept = 100 / 6, color = '#BA1B1D', linetype = "dashed") +
  labs(title = "Wired vs. Wireless")
```


```{r, echo=FALSE, fig.height=10}
#dat %>%
#  filter(WirelessConnection != "-") %>%
#  ggplot(aes(x = WirelessConnection, y = Latency, color = WirelessConnection)) +
#  geom_boxplot() +
#  scale_color_manual(values = c("Bluetooth" = '#2708A0', "2.4 GHz" = '#F9C80E')) +
#  theme(legend.position="none") +
#  geom_hline(yintercept = 100 / 6, color = '#BA1B1D', linetype = "dashed") +
#  xlab("Wireless Type") +
#  ylab("Latency (in ms)") +
#  labs(title = "Bluetooth vs. Generic 2.4 GHz")
```


```{r, echo=FALSE, warning=FALSE}
ggplot(dat) +
  geom_point(aes(x = 1:nrow(dat), y = `Latency (in ms)`, color = `Wired/Wireless`)) +
  scale_color_manual(values = c("Wired" = '#2708A0', "Wireless" = '#F9C80E')) +
  geom_hline(yintercept = 100 / 6, color = '#BA1B1D', linetype = "dashed") +
  xlab("Rank") +
  ylab("Latency (in ms)") +
  labs(title = "Latency by Rank")
```


```{r, echo=FALSE, fig.height=15}
dat %>%
  filter(`Wired/Wireless` == "Wired") %>%
  ggplot(aes(x = reorder(Device, desc(Device)), y = SD)) +
  geom_errorbar(aes(ymin=`SD down`, ymax=`SD up`, color = factor(Imputed, levels = c(TRUE, FALSE)))) +
  geom_hline(yintercept = 100 / 6, color = '#BA1B1D', linetype = "dashed") +
  geom_hline(yintercept = 0, color = '#2708A0') +
  coord_flip() +
  labs(caption = "NOTE: Due to limited data these ranges were imputed from the mean and standard deviation.
       They assume a normal distribution of values, (hence the occasional negative).
       Bars in red also had their standard deviation imputed from a multiple linear regression model.
       It's all very hand wavey, but should be accurate enough.",
       color = "Imputed") +
  xlab("Device") +
  ylab("Standard Deviation of Measured Latency (in ms)") +
  labs(title = "Approximate Wired Latency Ranges")
```


```{r, echo=FALSE, fig.height=10}
dat %>%
  filter(`Wired/Wireless` == "Wireless") %>%
  ggplot(aes(x = reorder(Device, desc(Device)), y = `Latency (in ms)`)) +
  geom_errorbar(aes(ymin=`SD down`, ymax=`SD up`, color = factor(Imputed, levels = c(TRUE, FALSE)))) +
  geom_hline(yintercept = 100 / 6, color = '#BA1B1D', linetype = "dashed") +
  geom_hline(yintercept = 0, color = '#2708A0') +
  coord_flip() +
  labs(caption = "NOTE: Due to limited data these ranges were imputed from the mean and standard deviation.
       They assume a normal distribution of values, (hence the occasional negative).
       Bars in red also had their standard deviation imputed from a multiple linear regression model.
       It's all very hand wavey, but should be accurate enough.",
       color = "Imputed") +
  xlab("Device") +
  ylab("Standard Deviation of Measured Latency (in ms)") +
  labs(title = "Approximate Wireless Latency Ranges")
```
